### ISSUE TITLE
Constructor for this has changed in 2.4

### ISSUE THREAD

**Issue by davidtisn** [Smile-SA/magento2-module-elasticsuite-quick-order#4] opened 2020-10-13 20:03 UTC
https://github.com/Smile-SA/magento2-module-elasticsuite-quick-order/blob/75118aeaaf70bbba40935779d37f0525fddbede0/Model/ResourceModel/Product/Suggest.php#L44

**Comment by rbayet** [comment] 2020-11-10 14:26
Duplicate of #3

**Closed as completed by rbayet** 2020-11-10 14:26 UTC
Labels: duplicate
